//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by ffdshow.rc
//
#define VERSION_RES_MINOR_VER           0
#define VERSION_RES_BUILD               0
#define VER_DEBUG                       0
#define VERSION_RES_MAJOR_VER           8
#define IDS_FFDSHOW                     9
#define IDD_ABOUT                       102
#define IDD_FFDSHOW                     111
#define IDI_FFDSHOW                     112
#define IDD_SUBTITLES                   113
#define IDD_CODECS                      115
#define IDD_INFO                        116
#define IDD_MISC                        118
#define IDD_PRESETS                     119
#define IDD_POSTPROC                    120
#define IDD_PICTPROP                    125
#define IDD_NOISE                       126
#define IDD_SHARPEN                     127
#define IDB_CHECKED                     127
#define IDD_BLUR                        128
#define IDB_CLEAR                       128
#define IDB_CHB_MASK                    129
#define IDD_FONT                        132
#define IDD_RESIZEASPECT                133
#define IDD_CROP                        134
#define IDD_DLGMISC                     136
#define IDD_OFFSET                      137
#define IDD_RESIZESETTINGS              138
#define IDB_ARROWS                      145
#define IDB_ARROWS_MASK_UD              146
#define IDB_ARROWS_MASK_U               147
#define IDR_MENU_PRESET                 147
#define IDB_ARROWS_MASK_D               148
#define ID_MNI_PRESET_RENAME            149
#define ID_MNI_PRESET_RENAMETOFILE      150
#define IDC_TBR_PPQUAL                  1002
#define IDC_TBR_ASPECT_USER             1002
#define IDC_TBR_LUMGAIN                 1003
#define IDC_TBR_HUE                     1004
#define IDC_TBR_RESIZE_SHARPEN_LUM      1004
#define IDC_TBR_LUMOFFSET               1005
#define IDC_TBR_SATURATION              1006
#define IDC_TBR_RESIZE_SHARPEN_CHROM    1006
#define IDC_TBR_GAMMA                   1007
#define IDC_CHB_AUTOQ                   1008
#define IDC_BT_LUMRESET                 1010
#define IDC_CHB_XVID                    1011
#define IDC_CHB_DIV3                    1012
#define IDC_CHB_DIVX                    1013
#define IDC_CHB_DX50                    1014
#define IDC_CHB_RAWV                    1015
#define IDC_CHB_FLIP                    1016
#define IDC_BT_PRESET_NEW               1016
#define IDC_CHB_DIVX_XVID               1016
#define IDC_LBL_LUMGAIN                 1017
#define IDC_BT_PRESET_NEW_MENU          1017
#define IDC_CHB_XVID_XVID               1017
#define IDC_LBL_LUMOFFSET               1018
#define IDC_BT_PRESET_RENAME_MENU       1018
#define IDC_CHB_DX50_XVID               1018
#define IDC_LBL_XSHARPENSTRENGTH        1019
#define IDC_LBL_RESIZE_SHARPEN_LUM      1019
#define IDC_TBR_XSHARPENSTRENGTH        1020
#define IDC_LBL_RESIZE_SHARPEN_CHROM    1020
#define IDC_LBL_XSHARPENTHRESH          1021
#define IDC_TBR_XSHARPENTHRESH          1022
#define IDC_CHB_MP42                    1023
#define IDC_TBR_BLUR_STRENGTH           1023
#define IDC_CHB_MP43                    1024
#define IDC_TBR_BLUR_TEMPSMOOTH         1024
#define IDC_LBL_HUE                     1025
#define IDC_CHB_MP41                    1025
#define IDC_LBL_SATURATION              1026
#define IDC_RBT_PPPRESETS               1027
#define IDC_RBT_PPCUSTOM                1028
#define IDC_CHB_DEBLOCKV_LUM            1029
#define IDC_CHB_DEBLOCKH_LUM            1030
#define IDC_CHB_DERING_LUM              1031
#define IDC_CHB_DEBLOCKV_CHROM          1032
#define VERSION_RES_LANGUAGE            0x409
#define IDC_CHB_DEBLOCKH_CHROM          1033
#define IDC_CHB_DERING_CHROM            1034
#define IDC_CHB_LEVELFIX_LUM            1035
#define IDC_CHB_LEVELFIX_CHROM          1036
#define IDC_LBL_GAMMA                   1037
#define IDC_CHB_NOISE                   1038
#define IDC_CHB_NOISE_UNIFORM           1039
#define IDC_TBR_NOISESTRENGTH           1040
#define IDC_LBL_NOISESTRENGTH           1041
#define IDC_BT_PRESET_REMOVE            1044
#define IDC_LBL_IDCT                    1045
#define IDC_BT_PRESET_RENAME            1045
#define IDC_CBX_IDCT                    1046
#define IDC_CHB_H263                    1048
#define IDC_LBL_NOISESTRENGTH_CHROMA    1049
#define IDC_CHB_H264                    1049
#define IDC_LBL_NOW_PLAYING             1050
#define IDC_CHB_AUTOPRESET              1051
#define IDC_CHB_H265                    1052
#define IDC_TBR_NOISESTRENGTH_CHROMA    1053
#define IDC_LBL_NOW_DIMENSIONS          1054
#define IDC_LBL_NOW_CODEC               1055
#define IDC_LBL_NOW_FPS                 1057
#define IDC_LBL_NOW_DECODERFPS          1058
#define IDC_LBL_NOW_FRAME               1059
#define IDC_RBT_SHARPEN_XSHARPEN        1063
#define IDC_RBT_SHARPEN_UNSHARPMASK     1064
#define IDC_CHB_SHARPEN                 1065
#define IDC_RBT_SHARPEN_WARPSHARP       1066
#define IDC_RBT_NOISE_MOJ               1067
#define IDC_RBT_NOISE_AVIH              1068
#define IDC_CHB_TRAYICON                1070
#define IDC_LBL_AVVERSION               1071
#define IDC_CHB_DLG_RESTOREPOS          1071
#define IDC_LBL_FFDSHOWVERSION          1072
#define IDC_CHB_PICTPROP                1072
#define IDC_CHB_POSTPROC                1073
#define IDC_LBL_XVIDVERSION             1073
#define IDC_CHB_SHOWMV                  1074
#define IDC_CHB_AUTOPRESET_FILEFIRST    1080
#define IDC_CHB_RESIZE                  1083
#define IDC_ED_RESIZEDX                 1084
#define IDC_ED_RESIZEDY                 1085
#define IDC_ED_CROP_TOP                 1086
#define IDC_ED_CROP_LEFT                1087
#define IDC_CHB_RESIZE_FIRST            1088
#define IDC_ED_CROP_RIGHT               1089
#define IDC_CBX_RESIZE_METHOD           1090
#define IDC_ED_CROP_BOTTOM              1092
#define IDC_LBL_ASPECT_USER             1096
#define IDC_LBL_RESIZE_GBLUR_LUM        1098
#define IDC_LBL_RESIZE_GBLUR_CHROM      1099
#define IDC_RBT_ASPECT_NO               1100
#define IDC_RBT_ASPECT_KEEP             1101
#define IDC_RBT_ASPECT_USER             1102
#define IDC_TBR_RESIZE_GBLUR_LUM        1103
#define IDC_TBR_RESIZE_GBLUR_CHROM      1104
#define IDC_CHB_SUBTITLES               1105
#define IDC_LBL_ZOOMX                   1105
#define IDC_TBR_ZOOMX                   1106
#define IDC_LBL_ZOOMY                   1107
#define IDC_LBL_FONT_WEIGHT             1108
#define IDC_TBR_ZOOMY                   1108
#define IDC_CBX_FONT_WEIGHT             1109
#define IDC_LBL_FONT_SIZE               1110
#define IDC_TBR_FONT_SIZE               1111
#define IDC_CBX_FONT_NAME               1112
#define IDC_CBX_FONT_CHARSET            1113
#define IDC_LBL_FONT_CHARSET            1114
#define IDC_LBL_FONT_SPACING            1116
#define IDC_TBR_FONT_SPACING            1117
#define IDC_LBL_FONT_SHADOW_STRENGTH    1118
#define IDC_TBR_FONT_SHADOW_STRENGTH    1119
#define IDC_BT_SUB_LOADFILE             1120
#define IDC_LBL_OFFSETUV_Y              1120
#define IDC_CBX_SUB_FLNM                1121
#define IDC_TBR_OFFSETUV_Y              1121
#define IDC_LBL_SUB_POSX                1122
#define IDC_TBR_SUB_POSX                1123
#define IDC_LBL_FONT_COLOR              1124
#define IDC_IMG_FONT_COLOR              1125
#define IDC_LBL_SUB_POSY                1126
#define IDC_TBR_SUB_POSY                1127
#define IDC_ED_SUB_DELAY                1128
#define IDC_ED_SUB_SPEED                1129
#define IDC_LBL_FONT_SHADOW_RADIUS      1130
#define IDC_TBR_FONT_SHADOW_RADIUS      1131
#define IDC_CHB_SUB_AUTOFLNM            1133
#define IDC_CHB_BLUR                    1134
#define IDC_LBL_BLUR_STRENGTH           1136
#define IDC_CHB_CROP                    1137
#define IDC_LBL_BLUR_TEMPSMOOTH         1137
#define IDC_RBT_ZOOM                    1138
#define IDC_RBT_CROP                    1139
#define IDC_CHB_MAGNIFICATION_LOCKED    1140
#define IDC_TV_TREE                     1141
#define IDC_ED_HELP                     1143
#define IDC_LV_PRESETS                  1144
#define IDC_CHB_OFFSET                  1148
#define IDC_LBL_OFFSETY_X               1149
#define IDC_TBR_OFFSETY_X               1150
#define IDC_LBL_OFFSETY_Y               1151
#define IDC_TBR_OFFSETY_Y               1152
#define IDC_LBL_OFFSETUV_X              1153
#define IDC_TBR_OFFSETUV_X              1154
#define IDC_BT_PRESET_SAVETOFILE        1155
#define IDC_BT_PRESET_READFROMFILE      1156
#define IDC_BT_PRESET_HELP              1157
#define IDC_LBL_DEBLOCKSTRENGTH         1158
#define IDC_TBR_DEBLOCKSTRENGTH         1159
#define VERSION_RES_CHARSET             1252
#define ID_MNI_PRESET_NEWFROMDEFAULT    40004
#define ID_MNI_PRESET_NEWFROMSELECTED   40005
#define ID_MNI_PRESET_NEW_FROMFILE      40006
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        154
#define _APS_NEXT_COMMAND_VALUE         40009
#define _APS_NEXT_CONTROL_VALUE         1160
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
