# Automatically generated by configure - do not modify
prefix=/usr/local
MAKE=make
#CC=/usr/local/gcc-3.1/bin/gcc
CC=gcc
AR=ar
OPTFLAGS=-O2 -march=i586 -mcpu=i686 -fomit-frame-pointer -finline
#OPTFLAGS=-O7 -march=athlon -mcpu=athlon -fomit-frame-pointer -finline -funroll-loops
TARGET_ARCH_X86=yes
TARGET_MMX=yes
BUILD_SHARED=yes
EXTRALIBS=-lm
VERSION=0.4.5
CONFIG_ENCODERS=no
CONFIG_DECODERS=yes
CONFIG_AC3=no
